"""Generate task-specific prompt sections for representative BabyAI environments.

For each environment family, resets the env several times to collect diverse
mission strings, then asks the LLM to generate the TASK SECTION of a system
prompt — the part that varies per task.

The fixed base (observation format, coordinate system, action definitions) is
hardcoded here since it is invariant across all MiniGrid environments.

Usage:
    python scripts/generate_task_prompts.py
    python scripts/generate_task_prompts.py --out prompts/task_sections
    python scripts/generate_task_prompts.py --samples 5 --model qwen/qwen3-4b
"""

from __future__ import annotations

import argparse
import logging
import sys
import textwrap
from pathlib import Path

import gymnasium as gym
import minigrid  # noqa: F401

from src.llm.client import OpenAIClient

log = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# One representative per task family.
# Chosen to cover the full breadth of task types without 95 LLM calls.
# ---------------------------------------------------------------------------
REPRESENTATIVE_ENVS = [
    # GoTo family
    "BabyAI-GoToRedBall-v0",       # simplest: single fixed target
    "BabyAI-GoToObj-v0",           # any named object
    "BabyAI-GoToDoor-v0",          # navigate to a door (no unlock)
    "BabyAI-GoToObjMaze-v0",       # multi-room navigation
    "BabyAI-GoToSeq-v0",           # sequential goto: "go to X after Y"
    # Pickup family
    "BabyAI-Pickup-v0",            # pick up a named object
    "BabyAI-PickupLoc-v0",         # pickup with location constraint
    "BabyAI-UnblockPickup-v0",     # move blocker, then pickup
    # Open / Door family
    "BabyAI-OpenDoor-v0",          # open a specific door
    "BabyAI-OpenTwoDoors-v0",      # open two doors in sequence
    "BabyAI-OpenDoorsOrderN2-v0",  # open doors in a specified order
    # Unlock family
    "BabyAI-Unlock-v0",            # find key → unlock door
    "BabyAI-UnlockPickup-v0",      # unlock room → pickup object inside
    "BabyAI-UnlockToUnlock-v0",    # chain of unlocks
    "BabyAI-KeyCorridor-v0",       # key corridor with multiple rooms
    # PutNext family
    "BabyAI-PutNextS4N1-v0",       # pick up X, drop next to Y
    "BabyAI-MoveTwoAcrossS5N2-v0", # move two objects
    # KeyInBox
    "BabyAI-KeyInBox-v0",          # key is inside a box; open box first
    # Mixed / Synth
    "BabyAI-Synth-v0",             # random mix of single instructions
    "BabyAI-SynthSeq-v0",          # sequential mixed instructions
    # Boss levels
    "BabyAI-MiniBossLevel-v0",
    "BabyAI-BossLevel-v0",
]

# ---------------------------------------------------------------------------
# Fixed base — invariant across all MiniGrid / BabyAI environments.
# The TASK SECTION generated by the LLM slots in after this.
# ---------------------------------------------------------------------------
FIXED_BASE = textwrap.dedent("""\
    ## Observation format
    You receive a 7x7 partial observation each step. The agent is always at
    position (row=6, col=3) in this view. Row 0 is directly ahead; row 6 is
    the agent's current row. Left and right are relative to the direction you
    are currently facing — they are NOT compass directions.

    ## Actions
    - left    : turn 90° left  (no movement)
    - right   : turn 90° right (no movement)
    - forward : move one step in the direction you are currently facing
    - pickup  : pick up the object directly in front of you (1 step ahead)
    - drop    : drop the object you are currently carrying
    - toggle  : open or unlock the door directly in front of you

    ## Response format
    Always reply with:
    PLAN: <short plan, or "No changes." if unchanged>
    ACTION: <one of: left, right, forward, pickup, drop, toggle>
""")

# ---------------------------------------------------------------------------
# Meta-prompt sent to the LLM
# ---------------------------------------------------------------------------
BOOTSTRAPPER_SYSTEM_PROMPT = textwrap.dedent("""\
    You are a prompt engineer specialising in grid-world agents.

    Your job is to write the TASK SECTION of a system prompt for an LLM-driven
    agent. A fixed base section already covers the observation format, action
    definitions, and response format — do not repeat any of that.

    The TASK SECTION must cover exactly these four things, in order:

    1. Win condition
       Precisely when does the episode end with success? Use action names and
       spatial terms (e.g. "1 step directly ahead") where relevant.

    2. Subgoal sequence
       For multi-step tasks list the ordered subgoals. For single-step tasks
       this can be one line.

    3. Key actions
       Which actions are central to completing this task and when should they
       be used? Be specific about preconditions (e.g. "toggle only when a door
       is 1 step directly ahead").

    4. Pitfalls
       At most three concrete mistakes the agent should avoid for this task.

    Be concise and concrete. Use action names exactly as defined above.
    Do not add headers beyond the four numbered sections.
    Do not mention the observation format or response format.
""")


def _collect_missions(env_id: str, n_samples: int, seed_start: int = 0) -> list[str]:
    """Reset an environment n_samples times and collect unique mission strings."""
    missions: list[str] = []
    try:
        env = gym.make(env_id)
        for i in range(n_samples):
            obs, _ = env.reset(seed=seed_start + i)
            mission = obs.get("mission", "")
            if mission and mission not in missions:
                missions.append(mission)
        env.close()
    except Exception as exc:
        log.warning("Could not sample %s: %s", env_id, exc)
    return missions


def _build_user_message(env_id: str, missions: list[str]) -> str:
    missions_block = "\n".join(f"  - {m}" for m in missions)
    return (
        f"Environment: {env_id}\n\n"
        f"Sample mission strings (collected from {len(missions)} resets):\n"
        f"{missions_block}\n\n"
        "Write the TASK SECTION for this environment."
    )


def generate_task_section(client: OpenAIClient, env_id: str, missions: list[str]) -> str:
    messages = [
        {"role": "system", "content": BOOTSTRAPPER_SYSTEM_PROMPT},
        {"role": "user",   "content": _build_user_message(env_id, missions)},
    ]
    return client.generate(messages)


def _format_report_entry(env_id: str, missions: list[str], task_section: str) -> str:
    divider = "=" * 70
    missions_block = "\n".join(f"  {m}" for m in missions)
    return (
        f"{divider}\n"
        f"Environment: {env_id}\n"
        f"{divider}\n\n"
        f"Sample missions:\n{missions_block}\n\n"
        f"--- FIXED BASE (invariant) ---\n"
        f"{FIXED_BASE}\n"
        f"--- GENERATED TASK SECTION ---\n"
        f"{task_section.strip()}\n\n"
    )


def parse_args():
    parser = argparse.ArgumentParser(description="Generate task prompt sections for BabyAI envs")
    parser.add_argument("--out",     default="prompts/task_sections", help="Output directory")
    parser.add_argument("--samples", type=int, default=5, help="Mission samples per environment")
    parser.add_argument("--model",   default=None, help="Override HLP_MODEL_ID env var")
    parser.add_argument("--envs",    nargs="*",    default=None,
                        help="Specific env IDs to run (default: all representatives)")
    return parser.parse_args()


def run(args):
    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)

    client_kwargs = {"model": args.model} if args.model else {}
    client = OpenAIClient(**client_kwargs)

    envs = args.envs or REPRESENTATIVE_ENVS
    report_lines: list[str] = [
        "BabyAI Task Prompt Sections\n"
        "Generated by scripts/generate_task_prompts.py\n\n"
    ]

    for i, env_id in enumerate(envs):
        print(f"[{i+1}/{len(envs)}] {env_id} ...", end=" ", flush=True)

        missions = _collect_missions(env_id, args.samples)
        if not missions:
            print("SKIPPED (could not sample)")
            continue

        try:
            task_section = generate_task_section(client, env_id, missions)
        except Exception as exc:
            print(f"LLM ERROR: {exc}")
            continue

        entry = _format_report_entry(env_id, missions, task_section)
        report_lines.append(entry)

        # Also write individual file per env for easy diff / inspection
        slug = env_id.replace("BabyAI-", "").replace("-v0", "").replace("-v1", "").lower()
        individual_path = out_dir / f"{slug}.txt"
        individual_path.write_text(
            f"Environment: {env_id}\n\n"
            f"Sample missions:\n" + "\n".join(f"  {m}" for m in missions) + "\n\n"
            f"{FIXED_BASE}\n"
            f"--- TASK SECTION ---\n"
            f"{task_section.strip()}\n",
            encoding="utf-8",
        )

        print(f"done  →  {individual_path.name}")

    report_path = out_dir / "all_tasks_report.txt"
    report_path.write_text("\n".join(report_lines), encoding="utf-8")
    print(f"\nFull report saved to: {report_path}")
    print(f"Individual files in:  {out_dir}/")


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, stream=sys.stderr)
    minigrid.register_minigrid_envs()
    run(parse_args())
